export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_RESET = "AUTH_RESET";
export const AUTH_SET_REDIRECT_PATH = "AUTH_SET_REDIRECT_PATH";

export const SOCKET_FETCH_FRIENDS_START = "SOCKET_FETCH_FRIEND_START";
export const SOCKET_FETCH_FRIENDS_SUCCESS = "SOCKET_FETCH_FRIEND_SUCCESS";
export const SOCKET_FETCH_FRIENDS_ERROR = "SOCKET_FETCH_FRIEND_ERROR";
export const SOCKET_FETCH_MESSAGES_START = "SOCKET_FETCH_MESSAGES_START";
export const SOCKET_FETCH_MESSAGES_SUCCESS = "SOCKET_FETCH_MESSAGES_SUCCESS";
export const SOCKET_FETCH_MESSAGES_ERROR = "SOCKET_FETCH_MESSAGES_ERROR";
