export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_RESET = "AUTH_RESET";
export const AUTH_SET_REDIRECT_PATH = "AUTH_SET_REDIRECT_PATH";

export const SOCKET_SET_ACTIVE_CHAT = "SOCKET_SET_ACTIVE_CHAT";
export const SOCKET_SHOW_ACTIVE_CHAT = "SOCKET_SHOW_ACTIVE_CHAT";

export const SOCKET_FETCH_START = "SOCKET_FETCH_FRIEND_START";
export const SOCKET_FETCH_FRIENDS_SUCCESS = "SOCKET_FETCH_FRIEND_SUCCESS";
export const SOCKET_FETCH_MESSAGES_SUCCESS = "SOCKET_FETCH_MESSAGES_SUCCESS";
export const SOCKET_FETCH_ERROR = "SOCKET_FETCH_FRIEND_ERROR";

export const SOCKET_UPDATE_INPUT = "SOCKET_UPDATE_INPUT";

export const SOCKET_CONNECTED = "SOCKET_CONNECTED";
export const SOCKET_DISCONNECTED = "SOCKET_DISCONNECTED";
export const SOCKET_EMIT_MESSAGE = "SOCKET_EMIT_MESSAGE";
export const SOCKET_EMIT_TYPING = "SOCKET_EMIT_TYPING";
export const SOCKET_EMIT_RECEIVED = "SOCKET_EMIT_RECEIVED";
export const SOCKET_EMIT_SEEN = "SOCKET_EMIT_SEEN";

export const SOCKET_ON_MESSAGE = "SOCKET_ON_MESSAGE";
export const SOCKET_ON_MESSAGE_SENT = "SOCKET_ON_MESSAGE_SENT";
export const SOCKET_ON_MESSAGE_STATE = "SOCKET_ON_MESSAGE_STATE";
export const SOCKET_ON_MESSAGE_DELETE = "SOCKET_ON_MESSAGE_DELETE";
export const SOCKET_ON_ONLINE = "SOCKET_ON_ONLINE";
export const SOCKET_ON_TYPING = "SOCKET_ON_TYPING";
