export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_RESET = "AUTH_RESET";
export const AUTH_SET_REDIRECT_PATH = "AUTH_SET_REDIRECT_PATH";

export const SOCKET_FETCH_START = "SOCKET_FETCH_FRIEND_START";
export const SOCKET_FETCH_FRIENDS_SUCCESS = "SOCKET_FETCH_FRIEND_SUCCESS";
export const SOCKET_FETCH_MESSAGES_SUCCESS = "SOCKET_FETCH_MESSAGES_SUCCESS";
export const SOCKET_FETCH_ERROR = "SOCKET_FETCH_FRIEND_ERROR";

export const SOCKET_CONNECTED = "SOCKET_CONNECTED";
export const SOCKET_DISCONNECTED = "SOCKET_DISCONNECTED";
export const SOCKET_SEND_MESSAGE = "SOCKET_SEND_MESSAGE";
export const SOCKET_TYPING_MESSAGE = "SOCKET_TYPING_MESSAGE";
export const SOCKET_RECEIVED_MESSAGE = "SOCKET_RECEIVED_MESSAGE";
export const SOCKET_SEEN_MESSAGE = "SOCKET_SEEN_MESSAGE";
